version: '3.8'
services:
  portfolio-v3-dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    image: portfolio-v3:dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
